### ISSUE TITLE
atualização

### ISSUE THREAD

**Issue by rogowski193** [launcherbr/whaticketsaas#1]
qual seria o valor para atualizarmos o sistema?
preciso de um auxilio para correr a atualização

**Comment by palmeirarocha** [comment]
Está já é a última versão, 4.8.5.

A atualização pode ser feita no próprio instalador.

cd instalador  && sudo ./install_primaria

Tem a opção de atualizar. Isto sendo uma instalação que veio deste mesmo endereço de repositório.

Se sua versão do whaticket for outra, que não essa Gold recomendo a instalação limpa. Porque vai apresentar problemas relacionados as tabelas do banco de dados.
